import {
  smartwatch1,
  smartwatch10,
  smartwatch11,
  smartwatch12,
  smartwatch2,
  smartwatch3,
  smartwatch4,
  smartwatch5,
  smartwatch6,
  smartwatch7,
  smartwatch8,
  smartwatch9,
} from "../assets/images/smartwatches";
import {
  canon1,
  canon2,
  canon3,
  canon4,
  canon5,
  leica1,
  leica2,
  leica3,
  leica4,
  leica5,
  lumix1,
  lumix2,
  lumix3,
  lumix4,
  lumix5,
  nikon1,
  nikon2,
  nikon3,
  nikon4,
  nikon5,
  sony1,
  sony2,
  sony3,
  sony4,
  sony5,
} from "../assets/images/cameraImgs";
import {
  drone1,
  drone10,
  drone2,
  drone3,
  drone4,
  drone5,
  drone6,
  drone7,
  drone8,
  drone9,
} from "../assets/images/droneImgs";
import {
  earbud1,
  earbud2,
  earbud3,
  earbud4,
  earbud5,
  earbud6,
  earbud7,
  earbud8,
  earbud9,
  earbud10,
  earbud11,
  earbud12,
  earbud13,
  earbud14,
  earbud15,
  onear1,
  onear2,
  onear3,
  onear4,
  onear5,
  onear6,
  onear7,
  onear8,
  onear9,
  onear10,
  onear11,
  onear12,
  onear13,
  onear14,
  onear15,
  speaker1,
  speaker2,
  speaker3,
  speaker4,
  speaker5,
} from "../assets/images/headphonesImgs";
import {
  iphone1,
  iphone2,
  iphone3,
  iphone4,
  iphone5,
  oneplus1,
  oneplus2,
  oneplus3,
  oneplus4,
  oneplus5,
  oneplus6,
  oneplus7,
  oneplus8,
  oneplus9,
  oneplus10,
  oppo1,
  oppo2,
  oppo3,
  oppo4,
  oppo5,
  oppo6,
  oppo7,
  oppo8,
  oppo9,
  oppo10,
  vivo1,
  vivo2,
  vivo3,
  vivo4,
  vivo5,
  vivo6,
  vivo7,
  vivo8,
  vivo9,
  vivo10,
} from "../assets/images/mobilesImgs";
import {
  asus1,
  asus10,
  asus2,
  asus3,
  asus4,
  asus5,
  asus6,
  asus7,
  asus8,
  asus9,
  dell1,
  dell10,
  dell2,
  dell3,
  dell4,
  dell5,
  dell6,
  dell7,
  dell8,
  dell9,
  hp1,
  hp10,
  hp2,
  hp3,
  hp4,
  hp5,
  hp6,
  hp7,
  hp8,
  hp9,
} from "../assets/images/laptopimgs";
import {
  samsung1,
  samsung2,
  samsung3,
  samsung4,
  samsung5,
  oneplustv1,
  oneplustv2,
  oneplustv3,
  oneplustv4,
  oneplustv5,
  xiaomi1,
  xiaomi2,
  xiaomi3,
  xiaomi4,
  xiaomi5,
  lg1,
  lg2,
  lg3,
  lg4,
  lg5,
  intex1,
  intex2,
  intex3,
  intex4,
  intex5,
} from "../assets/images/tvImgs";
const productData = [
  {
    id: 1,
    img: earbud1,
    title: "boat 441 pro",
    price: 3500,
    category: "earbud",
    description: "Premium wireless earbuds with advanced features.",
    type: "headphones",
  },
  {
    id: 2,
    img: earbud2,
    title: "Noise-Canceling Earbuds",
    price: 3000,
    category: "earbud",
    description:
      "Experience crystal-clear sound with active noise-canceling technology.",
    type: "headphones",
  },
  {
    id: 3,
    img: earbud3,
    title: "Sporty Wireless Earphones",
    price: 1500,
    category: "earbud",
    description:
      "Designed for sports enthusiasts with sweat-resistant features.",
    type: "headphones",
  },
  {
    id: 4,
    img: earbud4,
    title: "True Wireless Earbuds",
    price: 2000,
    category: "earbud",
    description:
      "Compact and lightweight true wireless earbuds for everyday use.",
    type: "headphones",
  },
  {
    id: 5,
    img: earbud5,
    title: "Bass-Boosted In-Ear Headphones",
    price: 1800,
    category: "earbud",
    description:
      "Enjoy deep bass and immersive audio with these in-ear headphones.",
    type: "headphones",
  },
  {
    id: 6,
    img: earbud6,
    title: "Wireless Earbuds with Touch Controls",
    price: 1200,
    category: "earbud",
    description:
      "Touch-sensitive controls for easy playback and calls on the go.",
    type: "headphones",
  },
  {
    id: 7,
    img: earbud7,
    title: "Sleek Metal Finish Earphones",
    price: 1400,
    category: "earbud",
    description: "Elegantly designed earphones with a durable metal finish.",
    type: "headphones",
  },
  {
    id: 8,
    img: earbud8,
    title: "Gaming Earbuds with Mic",
    price: 1800,
    category: "earbud",
    description:
      "Immerse yourself in gaming audio with these earbuds featuring a built-in microphone.",
    type: "headphones",
  },
  {
    id: 9,
    img: earbud9,
    title: "Dual Driver Hybrid Earphones",
    price: 2500,
    category: "earbud",
    description:
      "Experience a rich audio spectrum with dual-driver hybrid technology.",
    type: "headphones",
  },
  {
    id: 10,
    img: earbud10,
    title: "Wireless Earbuds for Fitness",
    price: 1300,
    category: "earbud",
    description:
      "Designed to stay in place during workouts, these earbuds are perfect for fitness enthusiasts.",
    type: "headphones",
  },
  {
    id: 11,
    img: earbud11,
    title: "Premium Wood-encased Earphones",
    price: 3800,
    category: "earbud",
    description:
      "Eco-friendly earphones with a premium wood finish for a unique look and feel.",
    type: "headphones",
  },
  {
    id: 12,
    img: earbud12,
    title: "Wireless Earbuds with Active EQ",
    price: 3200,
    category: "earbud",
    description:
      "Customize your audio experience with built-in active EQ technology.",
    type: "headphones",
  },
  {
    id: 13,
    img: earbud13,
    title: "Budget-Friendly Earbuds",
    price: 1100,
    category: "earbud",
    description: "Affordable yet reliable earbuds with clear sound quality.",
    type: "headphones",
  },
  {
    id: 14,
    img: earbud14,
    title: "In-Ear Monitors for Stage Performances",
    price: 4200,
    category: "earbud",
    description:
      "Designed for musicians and stage performers, these in-ear monitors deliver exceptional clarity.",
    type: "headphones",
  },
  {
    id: 15,
    img: earbud15,
    title: "High-Fidelity In-Ear Monitors",
    price: 4500,
    category: "earbud",
    description:
      "Professional-grade in-ear monitors for audiophiles and musicians.",
    type: "headphones",
  },
  {
    id: 16,
    img: onear1,
    title: "Premium On-Ear Headphones",
    price: 2999,
    category: "onear",
    description:
      "Experience high-quality sound and comfort with these premium on-ear headphones.",
    type: "headphones",
  },
  {
    id: 17,
    img: onear2,
    title: "Wireless Noise-Canceling On-Ear Headphones",
    price: 3999,
    category: "onear",
    description:
      "Enjoy wireless freedom and immersive sound with active noise-canceling technology.",
    type: "headphones",
  },
  {
    id: 18,
    img: onear3,
    title: "Foldable On-Ear Headphones for Travel",
    price: 2599,
    category: "onear",
    description:
      "Compact and foldable design makes these on-ear headphones perfect for travel.",
    type: "headphones",
  },
  {
    id: 19,
    img: onear4,
    title: "Bass-Enhanced On-Ear Headphones",
    price: 1799,
    category: "onear",
    description:
      "Immerse yourself in deep bass and rich audio with these on-ear headphones.",
    type: "headphones",
  },
  {
    id: 20,
    img: onear5,
    title: "Fashionable On-Ear Headphones",
    price: 1499,
    category: "onear",
    description:
      "Combine style and audio quality with these fashionable on-ear headphones.",
    type: "headphones",
  },
  {
    id: 21,
    img: onear6,
    title: "Sports On-Ear Headphones",
    price: 2199,
    category: "onear",
    description:
      "Designed for active individuals, these on-ear headphones stay in place during workouts.",
    type: "headphones",
  },
  {
    id: 22,
    img: onear7,
    title: "Wireless On-Ear Headphones with Touch Controls",
    price: 3299,
    category: "onear",
    description:
      "Control your music and calls effortlessly with touch-sensitive controls on these wireless on-ear headphones.",
    type: "headphones",
  },
  {
    id: 23,
    img: onear8,
    title: "Retro-Style On-Ear Headphones",
    price: 2699,
    category: "onear",
    description:
      "Experience a nostalgic vibe with these retro-style on-ear headphones while enjoying modern audio technology.",
    type: "headphones",
  },
  {
    id: 24,
    img: onear9,
    title: "Gaming On-Ear Headphones with Mic",
    price: 3499,
    category: "onear",
    description:
      "Immerse yourself in gaming audio and communicate clearly with the built-in microphone on these on-ear headphones.",
    type: "headphones",
  },
  {
    id: 25,
    img: onear10,
    title: "Boat 535",
    price: 4999,
    category: "onear",
    description:
      "Indulge in luxury and comfort with these leather-covered on-ear headphones that deliver premium audio quality.",
    type: "headphones",
  },
  {
    id: 26,
    img: onear11,
    title: "Wireless On-Ear Headphones for Work",
    price: 3799,
    category: "onear",
    description:
      "Stay focused during work with these wireless on-ear headphones designed for productivity.",
    type: "headphones",
  },
  {
    id: 27,
    img: onear12,
    title: "Active Noise-Canceling On-Ear Headphones",
    price: 4499,
    category: "onear",
    description:
      "Block out external noise and enjoy pure audio bliss with these active noise-canceling on-ear headphones.",
    type: "headphones",
  },
  {
    id: 28,
    img: onear13,
    title: "Ergonomic On-Ear Headphones",
    price: 2899,
    category: "onear",
    description:
      "Designed for comfort, these ergonomic on-ear headphones provide a snug fit for extended listening sessions.",
    type: "headphones",
  },
  {
    id: 29,
    img: onear14,
    title: "DJ-Style On-Ear Headphones",
    price: 3999,
    category: "onear",
    description:
      "Experience the beats like a DJ with these stylish on-ear headphones designed for music enthusiasts.",
    type: "headphones",
  },
  {
    id: 30,
    img: onear15,
    title: "High-Fidelity On-Ear Monitors",
    price: 4699,
    category: "onear",
    description:
      "For audiophiles seeking top-notch audio quality, these high-fidelity on-ear monitors deliver an exceptional listening experience.",
    type: "headphones",
  },
  {
    id: 31,
    img: speaker1,
    title: "Portable Bluetooth Speaker",
    price: 1499,
    category: "speaker",
    description:
      "Take your music anywhere with this compact and portable Bluetooth speaker.",
    type: "headphones",
  },
  {
    id: 32,
    img: speaker2,
    title: "Wireless Smart Speaker",
    price: 2999,
    category: "speaker",
    description:
      "Enjoy hands-free control and smart features with this wireless smart speaker compatible with virtual assistants.",
    type: "headphones",
  },
  {
    id: 33,
    img: speaker3,
    title: "High-Power Bookshelf Speakers",
    price: 3999,
    category: "speaker",
    description:
      "Transform your room with powerful audio using these high-power bookshelf speakers.",
    type: "headphones",
  },
  {
    id: 34,
    img: speaker4,
    title: "Waterproof Outdoor Speaker",
    price: 2499,
    category: "speaker",
    description:
      "Perfect for outdoor gatherings, this waterproof speaker can withstand the elements while delivering great sound.",
    type: "headphones",
  },
  {
    id: 35,
    img: speaker5,
    title: "Home Theater Soundbar System",
    price: 4499,
    category: "speaker",
    description:
      "Upgrade your home entertainment experience with this immersive home theater soundbar system.",
    type: "headphones",
  },
  //?Smartwatches start here
  {
    id: 36,
    img: smartwatch1,
    title: "Smartwatch Model A",
    price: 2000,
    company: "Firebolt",
    category: "Fitness",
    type: "Smartwatch",
    display: "AMOLED",
    description: "A feature-rich smartwatch for fitness enthusiasts.",
  },
  {
    id: 37,
    img: smartwatch2,
    title: "Smartwatch Model B",
    price: 2500,
    company: "Firebolt",
    category: "Multifunctional",
    type: "Smartwatch",
    display: "Super AMOLED",
    description: "A stylish and multifunctional smartwatch from Samsung.",
  },
  {
    id: 38,
    img: smartwatch3,
    title: "Fitness Tracker Pro",
    price: 1500,
    company: "Firebolt",
    category: "Fitness",
    type: "Smartwatch",
    display: "LED",
    description: "An affordable fitness tracker with essential features.",
  },
  {
    id: 39,
    img: smartwatch4,
    title: "Smartwatch X1",
    price: 3500,
    company: "Firebolt",
    category: "Multifunctional",
    type: "Smartwatch",
    display: "Retina",
    description: "The latest smartwatch from Apple with advanced features.",
  },
  {
    id: 40,
    img: smartwatch5,
    title: "Health Monitor Pro",
    price: 4000,
    company: "Firebolt",
    category: "Health",
    type: "Smartwatch",
    display: "Color Touchscreen",
    description: "A health monitor with advanced tracking capabilities.",
  },
  {
    id: 41,
    img: smartwatch6,
    title: "Outdoor Adventure Watch",
    price: 3200,
    company: "Firebolt",
    category: "Outdoor",
    type: "Smartwatch",
    display: "Dual-layer LCD",
    description:
      "Built for outdoor enthusiasts, with rugged design and features.",
  },
  {
    id: 42,
    img: smartwatch7,
    title: "Fashion Series Smartwatch",
    price: 3400,
    company: "Firebolt",
    category: "Fashion",
    type: "Smartwatch",
    display: "AMOLED",
    description: "A stylish smartwatch from Fossil's fashion series.",
  },
  {
    id: 43,
    img: smartwatch8,
    title: "Economy Fitness Tracker",
    price: 2200,
    company: "Firebolt",
    category: "Fitness",
    type: "Smartwatch",
    display: "Monochrome",
    description: "An affordable fitness tracker with basic functionalities.",
  },
  {
    id: 44,
    img: smartwatch9,
    title: "Classic Elegance Watch",
    price: 5000,
    company: "Firebolt",
    category: "Luxury",
    type: "Smartwatch",
    display: "Sapphire Crystal",
    description: "A luxurious and elegant smartwatch from TAG Heuer.",
  },
  {
    id: 45,
    img: smartwatch10,
    title: "Kids' Smartwatch",
    price: 4500,
    company: "Firebolt",
    category: "Kids",
    type: "Smartwatch",
    display: "Colorful Touchscreen",
    description: "A fun and educational smartwatch designed for kids.",
  },
  {
    id: 46,
    img: smartwatch11,
    title: "Professional Sports Watch",
    price: 3700,
    company: "Firebolt",
    category: "Sports",
    type: "Smartwatch",
    display: "High-Resolution",
    description:
      "Designed for professional athletes with advanced sports tracking.",
  },

  {
    id: 47,
    img: smartwatch12,
    title: "Slim and Sleek Smartwatch",
    price: 1500,
    company: "Firebolt",
    category: "Fashion",
    type: "Smartwatch",
    display: "AMOLED",
    description: "A slim and sleek smartwatch with advanced features.",
  },

  //?Mobiles Start Here

  {
    id: 61,
    img: iphone1,
    title: "iPhone 13 Pro",
    price: 70000,
    company: "Apple",
    category: "iOS",
    type: "mobiles",
    display: "amoled",
    processor: "Bionic",
    ram: "6 GB",
    storage: "128 GB",
    camera: "64mp",
    description:
      "The iPhone 13 Pro features a stunning Super AMOLED display, powerful A15 Bionic chip, and an advanced triple-camera system for exceptional photography.",
  },
  {
    id: 62,
    img: iphone2,
    title: "iPhone15 Pro",
    price: 90000,
    company: "Apple",
    category: "iOS",
    type: "mobiles",
    display: "oled",
    processor: "Bionic",
    ram: "4 GB",
    storage: "64 GB",
    camera: "64mp",
    description:
      "Experience the brilliance of the iPhone 12 with its vibrant OLED display, A14 Bionic chip, and dual-camera system for stunning photos and videos.",
  },
  {
    id: 63,
    img: iphone3,
    title: "iPhone SE (2020)",
    price: 35000,
    company: "Apple",
    category: "iOS",
    type: "mobiles",
    display: "oled",
    processor: "Bionic",
    ram: "3 GB",
    storage: "128 GB",
    camera: "100mp",
    description:
      "The iPhone SE (2020) combines the power of the A13 Bionic chip with a compact design, making it a perfect choice for those who prefer a smaller form factor.",
  },
  {
    id: 64,
    img: iphone4,
    title: "iPhone 11 Pro",
    price: 80000,
    company: "Apple",
    category: "iOS",
    type: "mobiles",
    display: "superamoled",
    processor: "Bionic",
    ram: "4 GB",
    storage: "256 GB",
    camera: "200mp",
    description:
      "Immerse yourself in the vivid Super Retina XDR display of the iPhone 11 Pro, coupled with the power of the A13 Bionic chip and a versatile triple-camera system.",
  },
  {
    id: 65,
    img: iphone5,
    title: "iPhone XR",
    price: 45000,
    company: "Apple",
    category: "iOS",
    type: "mobiles",
    display: "superamoled",
    processor: "A12 Bionic",
    ram: "3 GB",
    storage: "64 GB",
    camera: "200mp",
    description:
      "The iPhone XR features a brilliant Liquid Retina display, A12 Bionic chip, and a single-lens camera, delivering a premium iPhone experience at a more affordable price.",
  },
  {
    id: 66,
    img: oneplus1,
    title: "OnePlus 9 Pro",
    price: 69999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "128 GB",
    camera: "200mp",
    description:
      "The OnePlus 9 Pro boasts a Fluid AMOLED display, Snapdragon 888 processor, and a versatile quad-camera setup for stunning photography and performance.",
  },
  {
    id: 67,
    img: oneplus2,
    title: "OnePlus 8T",
    price: 42999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "Snapdragon 865",
    ram: "12 GB",
    storage: "256 GB",
    camera: "64mp",
    description:
      "Experience smooth performance and vibrant visuals with the OnePlus 8T, featuring a Fluid AMOLED display, Snapdragon 865 chipset, and a powerful quad-camera system.",
  },
  {
    id: 68,
    img: oneplus3,
    title: "OnePlus Nord 2",
    price: 29999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "100mp",
    description:
      "The OnePlus Nord 2 features a vibrant AMOLED display, MediaTek Dimensity 1200 processor, and a triple-camera system for a premium mid-range smartphone experience.",
  },
  {
    id: 69,
    img: oneplus4,
    title: "OnePlus 10Pro",
    price: 52999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "256 GB",
    camera: "48mp",
    description:
      "Immerse yourself in the stunning Fluid AMOLED display of the OnePlus 7 Pro, powered by the Snapdragon 855 chipset and equipped with a versatile triple-camera setup.",
  },
  {
    id: 70,
    img: oneplus5,
    title: "OnePlus 8",
    price: 39999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "Snapdragon",
    ram: "12 GB",
    storage: "128 GB",
    camera: "T64mp",
    description:
      "The OnePlus 8 features a Fluid AMOLED display, Snapdragon 865 processor, and a versatile triple-camera system, delivering a flagship experience at a competitive price.",
  },
  {
    id: 71,
    img: oneplus6,
    title: "OnePlus 9",
    price: 54999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "200mp",
    description:
      "Experience top-tier performance and photography with the OnePlus 9, featuring a Fluid AMOLED display, Snapdragon 888 chipset, and a triple-camera setup.",
  },
  {
    id: 72,
    img: oneplus7,
    title: "OnePlus Nord",
    price: 27999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Snapdragon",
    ram: "6 GB",
    storage: "64 GB",
    camera: "48mp",
    description:
      "The OnePlus Nord offers a smooth AMOLED display, Snapdragon 765G processor, and a versatile quad-camera system, making it an excellent choice for mid-range enthusiasts.",
  },
  {
    id: 73,
    img: oneplus8,
    title: "OnePlus 7T",
    price: 34999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "128 GB",
    camera: "64mp",
    description:
      "Upgrade to flagship performance with the OnePlus 7T, featuring a Fluid AMOLED display, Snapdragon 855+ chipset, and a powerful triple-camera system.",
  },
  {
    id: 74,
    img: oneplus9,
    title: "OnePlus Nord CE 5G",
    price: 22999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "MeadiaTek",
    ram: "6 GB",
    storage: "128 GB",
    camera: "200mp",
    description:
      "The OnePlus Nord CE 5G offers a Fluid AMOLED display, Snapdragon 750G processor, and a triple-camera system for a compelling 5G-enabled mid-range experience.",
  },
  {
    id: 75,
    img: oneplus10,
    title: "OnePlus 6T",
    price: 32999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "128 GB",
    camera: "100mp",
    description:
      "The OnePlus 6T features a vibrant AMOLED display, Snapdragon 845 processor, and a dual-camera system for a flagship-like experience at an affordable price.",
  },
  {
    id: 76,
    img: oppo1,
    title: "Oppo Find X3 Pro",
    price: 74999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Snapdragon",
    ram: "12 GB",
    storage: "256 GB",
    camera: "48mp",
    description:
      "Explore the excellence of the Oppo Find X3 Pro with its vibrant AMOLED display, Snapdragon 888 processor, and a cutting-edge quad-camera system for exceptional photography and performance.",
  },
  {
    id: 77,
    img: oppo2,
    title: "Oppo Reno6 Pro+",
    price: 54999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "64mp",
    description:
      "Experience the Oppo Reno6 Pro+ with its stunning AMOLED display, Dimensity 1200 processor, and a powerful quad-camera setup for impressive photography and smooth performance.",
  },
  {
    id: 78,
    img: oppo3,
    title: "Oppo F19 Pro+",
    price: 27999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "48mp",
    description:
      "The Oppo F19 Pro+ features a Super AMOLED display, MediaTek Dimensity 800U processor, and a versatile quad-camera system, delivering a compelling mid-range smartphone experience.",
  },
  {
    id: 79,
    img: oppo4,
    title: "Oppo A74 5G",
    price: 19999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Snapdragon",
    ram: "6 GB",
    storage: "128 GB",
    camera: "48mp",
    description:
      "Enjoy the Oppo A74 5G with its smooth 90Hz IPS LCD display, Snapdragon 480 processor, and a triple-camera system, providing a great 5G-enabled experience at an affordable price.",
  },
  {
    id: 80,
    img: oppo5,
    title: "Oppo Reno5 Pro",
    price: 35999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "64mp",
    description:
      "Immerse yourself in the Oppo Reno5 Pro's Super AMOLED display, powered by the Dimensity 1000+ processor and featuring a quad-camera system for impressive photography.",
  },
  {
    id: 81,
    img: oppo6,
    title: "Oppo A15",
    price: 9999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Mediatek",
    ram: "3 GB",
    storage: "32 GB",
    camera: "48mp",
    description:
      "The Oppo A15 offers an affordable package with its IPS LCD display, Mediatek Helio P35 processor, and a triple-camera system for everyday photography needs.",
  },
  {
    id: 82,
    img: oppo7,
    title: "Oppo F17 Pro",
    price: 22990,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "Mediatek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "100mp",
    description:
      "The Oppo F17 Pro combines style with performance, featuring a Super AMOLED display, Mediatek Helio P95 processor, and a versatile quad-camera system.",
  },
  {
    id: 83,
    img: oppo8,
    title: "Oppo A53",
    price: 12990,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Snapdragon",
    ram: "4 GB",
    storage: "64 GB",
    camera: "48mp",
    description:
      "The Oppo A53 offers a smooth experience with its 90Hz IPS LCD display, Snapdragon 460 processor, and a triple-camera system for everyday photography needs.",
  },
  {
    id: 84,
    img: oppo9,
    title: "Oppo Reno4 Pro",
    price: 34990,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "128 GB",
    camera: "200mp",
    description:
      "Experience creativity with the Oppo Reno4 Pro, featuring a Super AMOLED display, Snapdragon 720G processor, and a versatile quad-camera system for stunning visuals.",
  },
  {
    id: 85,
    img: oppo10,
    title: "Oppo A12",
    price: 9999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Mediatek",
    ram: "3 GB",
    storage: "32 GB",
    camera: "48mp",
    description:
      "The Oppo A12 provides essential features with its IPS LCD display, Mediatek Helio P35 processor, and a dual-camera system for a budget-friendly smartphone experience.",
  },
  {
    id: 86,
    img: vivo1,
    title: "Vivo X60 Pro+",
    price: 69990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "Snapdragon",
    ram: "12 GB",
    storage: "256 GB",
    camera: "200mp",
    description:
      "Capture the extraordinary with the Vivo X60 Pro+, featuring a vibrant AMOLED display, Snapdragon 888 processor, and a professional-grade quad-camera system for stunning photography and performance.",
  },
  {
    id: 87,
    img: vivo2,
    title: "Vivo V21e",
    price: 24990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "64mp",
    description:
      "Experience sleek design and powerful performance with the Vivo V21e, featuring an AMOLED display, Dimensity 800U processor, and a dual-camera system for impressive photography.",
  },
  {
    id: 88,
    img: vivo3,
    title: "Vivo Y73",
    price: 20990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "48mp",
    description:
      "Elevate your mobile experience with the Vivo Y73, featuring an AMOLED display, MediaTek Helio G95 processor, and a triple-camera system for versatile photography.",
  },
  {
    id: 89,
    img: vivo4,
    title: "Vivo X50 Pro",
    price: 49990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "256 GB",
    camera: "100mp",
    description:
      "Unleash creativity with the Vivo X50 Pro, featuring an AMOLED display, Snapdragon 765G processor, and a versatile quad-camera system for exceptional photography and stability.",
  },
  {
    id: 90,
    img: vivo5,
    title: "Vivo S1 Pro",
    price: 19990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "128 GB",
    camera: "48mp",
    description:
      "Step into style and performance with the Vivo S1 Pro, featuring a Super AMOLED display, Snapdragon 665 processor, and a versatile quad-camera system for everyday photography needs.",
  },
  {
    id: 91,
    img: vivo6,
    title: "Vivo Y20G",
    price: 12990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "MediaTek",
    ram: "6 GB",
    storage: "128 GB",
    camera: "48mp",
    description:
      "The Vivo Y20G offers a budget-friendly option with its IPS LCD display, MediaTek Helio G80 processor, and a triple-camera system for essential photography needs.",
  },
  {
    id: 92,
    img: vivo7,
    title: "Vivo V17",
    price: 22990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "128 GB",
    camera: "100mp",
    description:
      "Experience brilliance with the Vivo V17, featuring a Super AMOLED display, Snapdragon 675 processor, and a versatile quad-camera system for impressive photography.",
  },
  {
    id: 93,
    img: vivo8,
    title: "Vivo Y30",
    price: 14990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "MediaTek",
    ram: "4 GB",
    storage: "128 GB",
    camera: "48mp",
    description:
      "The Vivo Y30 offers a balance of features with its IPS LCD display, MediaTek Helio P35 processor, and a quad-camera system for a budget-friendly smartphone experience.",
  },
  {
    id: 94,
    img: vivo9,
    title: "Vivo V21",
    price: 29990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "100mp",
    description:
      "Experience sleek design and advanced features with the Vivo V21, featuring an AMOLED display, Dimensity 800U processor, and a triple-camera system for stunning photography.",
  },
  {
    id: 95,
    img: vivo10,
    title: "Vivo Y12s",
    price: 10990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "MediaTek",
    ram: "3 GB",
    storage: "32 GB",
    camera: "48mp",
    description:
      "The Vivo Y12s offers essential features with its IPS LCD display, MediaTek Helio P35 processor, and a dual-camera system for a budget-friendly smartphone experience.",
  },
  //?laptop data
  {
    id: 96,
    img: asus1,
    title: "asus vivobook 11",
    price: 52999,
    company: "asus",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for Asus Vivobook 11. It comes with a vibrant OLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 97,
    img: asus2,
    title: "asus Zenbook 15",
    price: 95999,
    company: "asus",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "intel",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Chromebook. It features an AMOLED display, Intel processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 98,
    img: asus3,
    title: "asus notebook 12",
    price: 54999,
    company: "asus",
    category: "notebook",
    type: "laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 99,
    img: asus4,
    title: "asus notebook 15",
    price: 58999,
    company: "asus",
    category: "notebook",
    type: "laptop",
    display: "superamoled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for Asus Notebook 15. It features a Super AMOLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 100,
    img: asus5,
    title: "asus notebook 14",
    price: 55999,
    company: "asus",
    category: "notebook",
    type: "laptop",
    display: "superamoled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for Asus Notebook 14. It features a Super AMOLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 101,
    img: asus6,
    title: "asus notebook 13",
    price: 56999,
    company: "asus",
    category: "notebook",
    type: "laptop",
    display: "superamoled",
    processor: "ryzen",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Notebook 13. It features a Super AMOLED display, Ryzen processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 102,
    img: asus7,
    title: "asus chromebook",
    price: 57999,
    company: "asus",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "ryzen",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Chromebook. It features an AMOLED display, Ryzen processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 103,
    img: asus8,
    title: "asus chromebook",
    price: 58999,
    company: "asus",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "ryzen",
    ram: "32 GB",
    ssd: "256 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Chromebook. It features an AMOLED display, Ryzen processor, 32 GB RAM, and spacious storage options.",
  },
  {
    id: 104,
    img: asus9,
    title: "asus chromebook",
    price: 59999,
    company: "asus",
    category: "chromebook",
    type: "laptop",
    display: "oled",
    processor: "ryzen",
    ram: "32 GB",
    ssd: "256 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Chromebook. It features an OLED display, Ryzen processor, 32 GB RAM, and spacious storage options.",
  },
  {
    id: 105,
    img: asus10,
    title: "asus chromebook",
    price: 62999,
    company: "asus",
    category: "chromebook",
    type: "laptop",
    display: "oled",
    processor: "ryzen",
    ram: "32 GB",
    ssd: "256 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Chromebook. It features an OLED display, Ryzen processor, 32 GB RAM, and spacious storage options.",
  },

  {
    id: 106,
    img: dell1,
    title: "dell vivobook 11",
    price: 52999,
    company: "dell",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for dell Vivobook 11. It comes with a vibrant OLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 107,
    img: dell2,
    title: "dell chromebook",
    price: 53999,
    company: "dell",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "ryzen",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Chromebook. It features an AMOLED display, ryzen processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 108,
    img: dell3,
    title: "dell notebook 12",
    price: 54999,
    company: "dell",
    category: "notebook",
    type: "laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 109,
    img: dell4,
    title: "dell vivobook 11",
    price: 52999,
    company: "dell",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "ryzen",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for dell Vivobook 11. It comes with a vibrant OLED display, ryzen processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 110,
    img: dell5,
    title: "dell chromebook",
    price: 53999,
    company: "dell",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "intel",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Chromebook. It features an AMOLED display, Intel processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 111,
    img: dell6,
    title: "dell notebook 12",
    price: 54999,
    company: "dell",
    category: "notebook",
    type: "laptop",
    display: "superamoled",
    processor: "ryzen",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Notebook 12. It features a Super AMOLED display, Ryzen processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 112,
    img: dell7,
    title: "dell vivobook 11",
    price: 52999,
    company: "dell",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for dell Vivobook 11. It comes with a vibrant OLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 113,
    img: dell8,
    title: "dell chromebook",
    price: 53999,
    company: "dell",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "ryzen",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Chromebook. It features an AMOLED display, ryzen processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 114,
    img: dell9,
    title: "dell notebook 12",
    price: 54999,
    company: "dell",
    category: "notebook",
    type: "laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 115,
    img: dell10,
    title: "dell notebook 12",
    price: 54999,
    company: "dell",
    category: "notebook",
    type: "laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },

  {
    id: 116,
    img: hp1,
    title: "hp vivobook 11",
    price: 52999,
    company: "hp",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for hp Vivobook 11. It comes with a vibrant OLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 117,
    img: hp2,
    title: "hp chromebook",
    price: 53999,
    company: "hp",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "ryzen",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Chromebook. It features an AMOLED display, ryzen processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 118,
    img: hp3,
    title: "hp notebook 12",
    price: 54999,
    company: "hp",
    category: "notebook",
    type: "laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 119,
    img: hp4,
    title: "hp vivobook 11",
    price: 52999,
    company: "hp",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "ryzen",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for hp Vivobook 11. It comes with a vibrant OLED display, ryzen processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 120,
    img: hp5,
    title: "hp chromebook",
    price: 53999,
    company: "hp",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "intel",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Chromebook. It features an AMOLED display, Intel processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 121,
    img: hp6,
    title: "hp notebook 12",
    price: 54999,
    company: "hp",
    category: "notebook",
    type: "laptop",
    display: "superamoled",
    processor: "ryzen",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Notebook 12. It features a Super AMOLED display, ryzen processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 122,
    img: hp7,
    title: "hp vivobook 11",
    price: 52999,
    company: "hp",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for hp Vivobook 11. It comes with a vibrant OLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 123,
    img: hp8,
    title: "hp chromebook",
    price: 53999,
    company: "hp",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "ryzen",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Chromebook. It features an AMOLED display, ryzen processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 124,
    img: hp9,
    title: "hp notebook 12",
    price: 54999,
    company: "hp",
    category: "notebook",
    type: "laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 125,
    img: hp10,
    title: "hp notebook 12",
    price: 54999,
    company: "hp",
    category: "notebook",
    type: "laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 126,
    img: drone1,
    title: "drone x",
    price: 2999,
    company: "xavier",
    category: "multirotor",
    type: "drone",
    display: "oled",
    storage: "120 GB",
    ram: "8 GB",
    camera: "48mp",
    description:
      "This is the description for drone X . It comes with a vibrant OLED display, 120 GB storage, 8 GB RAM, and ample camera options.",
  },
  {
    id: 127,
    img: drone2,
    title: "drone y",
    price: 3999,
    company: "xavier",
    category: "singlerotor",
    type: "drone",
    display: "amoled",
    storage: "120 GB",
    ram: "16 GB",
    camera: "48mp",
    description:
      "This is the description for drone y. It features an AMOLED display, 120 GB storage, 16 GB RAM, and spacious camera options.",
  },
  {
    id: 128,
    img: drone3,
    title: "drone x",
    price: 4999,
    company: "xavier",
    category: "multirotor",
    type: "drone",
    display: "superamoled",
    storage: "120 GB",
    ram: "32 GB",
    camera: "48mp",
    description:
      "This is the description for drone  v. It features a Super AMOLED display, 120 GB storage, 32 GB RAM, and ample camera options.",
  },
  {
    id: 129,
    img: drone4,
    title: "drone y",
    price: 2999,
    company: "xavier",
    category: "multirotor",
    type: "drone",
    display: "oled",
    storage: "120 GB",
    ram: "8 GB",
    camera: "48mp",
    description:
      "This is the description for drone . It comes with a vibrant OLED display, 120 GB storage, 8 GB RAM, and ample camera options.",
  },
  {
    id: 130,
    img: drone5,
    title: "drone x",
    price: 3999,
    company: "nx",
    category: "singlerotor",
    type: "drone",
    display: "amoled",
    storage: "120 GB",
    ram: "16 GB",
    camera: "48mp",
    description:
      "This is the description for drone y. It features an AMOLED display, 120 GB storage, 16 GB RAM, and spacious camera options.",
  },
  {
    id: 131,
    img: drone6,
    title: "drone y",
    price: 4999,
    company: "xavier",
    category: "multirotor",
    type: "drone",
    display: "superamoled",
    storage: "240 GB",
    ram: "32 GB",
    camera: "48mp",
    description:
      "This is the description for drone . It features a Super AMOLED display, 240 GB storage, 32 GB RAM, and ample camera options.",
  },
  {
    id: 132,
    img: drone7,
    title: "drone v",
    price: 5999,
    company: "nx",
    category: "multirotor",
    type: "drone",
    display: "oled",
    storage: "240 GB",
    ram: "8 GB",
    camera: "48mp",
    description:
      "This is the description for drone . It comes with a vibrant OLED display, 240 GB storage, 8 GB RAM, and ample camera options.",
  },
  {
    id: 133,
    img: drone8,
    title: "drone x",
    price: 3999,
    company: "nx",
    category: "singlerotor",
    type: "drone",
    display: "amoled",
    storage: "240 GB",
    ram: "16 GB",
    camera: "48mp",
    description:
      "This is the description for drone y. It features an AMOLED display, 240 GB storage, 16 GB RAM, and spacious camera options.",
  },
  {
    id: 134,
    img: drone9,
    title: "drone y ",
    price: 5999,
    company: "nx",
    category: "multirotor",
    type: "drone",
    display: "superamoled",
    storage: "240 GB",
    ram: "32 GB",
    camera: "48mp",
    description:
      "This is the description for drone. It features a Super AMOLED display, 240 GB storage, 32 GB RAM, and ample camera options.",
  },
  {
    id: 135,
    img: drone10,
    title: "drone x",
    price: 4999,
    company: "nx",
    category: "multirotor",
    type: "drone",
    display: "superamoled",
    storage: "240 GB",
    ram: "32 GB",
    camera: "48mp",
    description:
      "This is the description for drone . It features a Super AMOLED display, 240 GB storage, 32 GB RAM, and ample camera options.",
  },
  {
    id: 136,
    img: samsung1,
    title: "Samsung 32",
    price: 22999,
    company: "Samsung",
    type: "tv",
    display: "hd",
    size: 32,
    year: 2022,
    description:
      "Enjoy a captivating viewing experience with our 32-inch HD TV from Samsung. Immerse yourself in high-definition visuals and vibrant colors for an enhanced entertainment journey.",
  },
  {
    id: 137,
    img: samsung2,
    title: "Samsung 43",
    price: 32999,
    company: "Samsung",
    type: "tv",
    display: "fullhd",
    size: 43,
    year: 2023,
    description:
      "Upgrade your home theater with our 43-inch Full HD TV from Samsung. Immerse yourself in detailed visuals and crisp images for an unparalleled viewing pleasure.",
  },
  {
    id: 138,
    img: samsung3,
    title: "Samsung 55",
    price: 52999,
    company: "Samsung",
    type: "tv",
    display: "4k",
    size: 55,
    year: 2024,
    description:
      "Experience the future of entertainment with our 55-inch 4K TV from Samsung. Enjoy stunning visuals, lifelike details, and vibrant colors for a cinematic experience at home.",
  },
  {
    id: 139,
    img: samsung4,
    title: "Samsung Neo56",
    price: 52999,
    company: "Samsung",
    type: "tv",
    display: "4k",
    size: 55,
    year: 2024,
    description:
      "Elevate your viewing experience with our 55-inch 4K TV from Samsung. Immerse yourself in ultra-high-definition resolution and vibrant colors for an extraordinary cinematic journey.",
  },
  {
    id: 140,
    img: samsung5,
    title: "Samsung 57",
    price: 52999,
    company: "Samsung",
    type: "tv",
    display: "4k",
    size: 55,
    year: 2024,
    description:
      "Immerse yourself in the world of entertainment with our 55-inch 4K TV from Samsung. Experience breathtaking visuals and a cinematic atmosphere in the comfort of your home.",
  },
  {
    id: 141,
    img: oneplustv1,
    title: "OnePlus 32",
    price: 22999,
    company: "Oneplustv",
    type: "tv",
    display: "hd",
    size: 32,
    year: 2022,
    description:
      "Immerse yourself in high-definition entertainment with our 32-inch HD TV from OnePlus. Enjoy a clear and vibrant viewing experience for your favorite content.",
  },
  {
    id: 142,
    img: oneplustv2,
    title: "OnePlus 42",
    price: 42999,
    company: "Oneplustv",
    type: "tv",
    display: "fullhd",
    size: 42,
    year: 2023,
    description:
      "Upgrade your home theater with our 42-inch Full HD TV from OnePlus. Immerse yourself in detailed visuals and vibrant colors for an enhanced viewing pleasure.",
  },
  {
    id: 143,
    img: oneplustv3,
    title: "OnePlus 55",
    price: 52999,
    company: "Oneplustv",
    type: "tv",
    display: "4k",
    size: 55,
    year: 2024,
    description:
      "Experience the future of entertainment with our 55-inch 4K TV from OnePlus. Enjoy stunning visuals and lifelike details for a cinematic experience at home.",
  },
  {
    id: 144,
    img: oneplustv4,
    title: "OnePlus 56",
    price: 52999,
    company: "Oneplustv",
    type: "tv",
    display: "4k",
    size: 55,
    year: 2024,
    description:
      "Elevate your viewing experience with our 55-inch 4K TV from OnePlus. Immerse yourself in ultra-high-definition resolution and vibrant colors for an extraordinary cinematic journey.",
  },
  {
    id: 145,
    img: oneplustv5,
    title: "OnePlus 57",
    price: 52999,
    company: "Oneplustv",
    type: "tv",
    display: "4k",
    size: 55,
    year: 2024,
    description:
      "Immerse yourself in the world of entertainment with our 55-inch 4K TV from OnePlus. Experience breathtaking visuals and a cinematic atmosphere in the comfort of your home.",
  },
  {
    id: 146,
    img: xiaomi1,
    title: "Xiaomi 32",
    price: 22999,
    company: "Xiaomi",
    type: "tv",
    display: "hd",
    size: 32,
    year: 2022,
    description:
      "Experience entertainment like never before with our 32-inch HD TV from Xiaomi. Enjoy clear visuals and vibrant colors for an immersive viewing experience.",
  },
  {
    id: 147,
    img: xiaomi2,
    title: "Xiaomi 33",
    price: 22999,
    company: "Xiaomi",
    type: "tv",
    display: "hd",
    size: 32,
    year: 2022,
    description:
      "Upgrade your home entertainment setup with our 32-inch HD TV from Xiaomi. Immerse yourself in high-quality visuals and enjoy your favorite content with clarity.",
  },
  {
    id: 148,
    img: xiaomi3,
    title: "Xiaomi 42",
    price: 42999,
    company: "Xiaomi",
    type: "tv",
    display: "fullhd",
    size: 42,
    year: 2023,
    description:
      "Transform your living room with our 42-inch Full HD TV from Xiaomi. Immerse yourself in stunning visuals and vibrant colors for an enhanced viewing experience.",
  },
  {
    id: 149,
    img: xiaomi4,
    title: "Xiaomi 55",
    price: 52999,
    company: "Xiaomi",
    type: "tv",
    display: "4k",
    size: 55,
    year: 2024,
    description:
      "Step into the future of entertainment with our 55-inch 4K TV from Xiaomi. Enjoy breathtaking visuals and lifelike details for a cinematic experience at home.",
  },
  {
    id: 150,
    img: xiaomi5,
    title: "Xiaomi 56",
    price: 52999,
    company: "Xiaomi",
    type: "tv",
    display: "4k",
    size: 55,
    year: 2024,
    description:
      "Elevate your home entertainment with our 55-inch 4K TV from Xiaomi. Immerse yourself in ultra-high-definition resolution and vibrant colors for an extraordinary viewing experience.",
  },
  {
    id: 151,
    img: lg1,
    title: "LG 32",
    price: 22999,
    company: "LG",
    type: "tv",
    display: "hd",
    size: 32,
    year: 2024,
    description:
      "Immerse yourself in high-definition entertainment with our 32-inch HD TV from LG. Enjoy vivid visuals and a crisp viewing experience.",
  },
  {
    id: 152,
    img: lg2,
    title: "LG 42",
    price: 42999,
    company: "LG",
    type: "tv",
    display: "fullhd",
    size: 42,
    year: 2023,
    description:
      "Upgrade your home theater with our 42-inch Full HD TV from LG. Experience vibrant colors and detailed images for an enhanced viewing pleasure.",
  },
  {
    id: 153,
    img: lg3,
    title: "LG 55",
    price: 52999,
    company: "LG",
    type: "tv",
    display: "4k",
    size: 55,
    year: 2024,
    description:
      "Step into the future of entertainment with our 55-inch 4K TV from LG. Enjoy stunning visuals and lifelike details for a cinematic experience at home.",
  },
  {
    id: 154,
    img: lg4,
    title: "LG 43",
    price: 42999,
    company: "LG",
    type: "tv",
    display: "fullhd",
    size: 42,
    year: 2023,
    description:
      "Enhance your viewing experience with our 42-inch Full HD TV from LG. Immerse yourself in clear visuals and dynamic colors for an unforgettable entertainment journey.",
  },
  {
    id: 155,
    img: lg5,
    title: "LG 54",
    price: 52999,
    company: "LG",
    type: "tv",
    display: "4k",
    size: 55,
    year: 2024,
    description:
      "Elevate your home entertainment with our 55-inch 4K TV from LG. Enjoy a breathtaking visual experience with ultra-high-definition resolution and vibrant colors.",
  },
  {
    id: 156,
    img: intex1,
    title: "Intex 32",
    price: 22999,
    company: "intex",
    type: "tv",
    display: "hd",
    size: 32,
    year: 2022,
    description:
      "Enjoy a stunning visual experience with our 32-inch HD TV from Intex. High-definition display technology for crisp and clear images.",
  },
  {
    id: 157,
    img: intex2,
    title: "Intex 42",
    price: 42999,
    company: "intex",
    type: "tv",
    display: "fullhd",
    size: 42,
    year: 2023,
    description:
      "Immerse yourself in vibrant colors and sharp details with our 42-inch Full HD TV from Intex. Advanced display technology for an enhanced viewing experience.",
  },
  {
    id: 158,
    img: intex3,
    title: "Intex 55",
    price: 52999,
    company: "intex",
    type: "tv",
    display: "4k",
    size: 55,
    year: 2024,
    description:
      "Experience the future of entertainment with our 55-inch 4K TV from Intex. Ultra-high-definition resolution for a cinematic experience at home.",
  },
  {
    id: 159,
    img: intex4,
    title: "Intex 43",
    price: 42999,
    company: "intex",
    type: "tv",
    display: "fullhd",
    size: 42,
    year: 2023,
    description:
      "Upgrade your viewing experience with our 42-inch Full HD TV from Intex. Crystal-clear visuals and vibrant colors for an immersive experience.",
  },
  {
    id: 160,
    img: intex5,
    title: "Intex 44",
    price: 42999,
    company: "intex",
    type: "tv",
    display: "fullhd",
    size: 42,
    year: 2023,
    description:
      "Bring home the ultimate entertainment package with our 42-inch Full HD TV from Intex. Sleek design and impressive display for an enhanced setup.",
  },
  {
    id: 161,
    img: nikon1,
    title: "nikon 44",
    price: 42999,
    company: "nikon",
    type: "camera",
    resolution: "24mp",
    fileformat: "jpeg",
    description:
      "The Nikon 44 is a high-quality camera with 24 megapixels resolution and JPEG file format support. Capture stunning images with ease.",
  },
  {
    id: 162,
    img: nikon2,
    title: "nikon 43",
    price: 43999,
    company: "nikon",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Experience superior image quality with the Nikon 43. It features a powerful 30-megapixel sensor and supports RAW file format for professional photographers.",
  },
  {
    id: 163,
    img: nikon3,
    title: "nikon 44",
    price: 42999,
    company: "nikon",
    type: "camera",
    resolution: "24mp",
    fileformat: "raw",
    description:
      "Unleash your creativity with the Nikon 44. This camera boasts a 24-megapixel resolution and supports RAW file format, providing flexibility in post-processing.",
  },
  {
    id: 164,
    img: nikon4,
    title: "nikon 43",
    price: 45999,
    company: "nikon",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Upgrade your photography game with the Nikon 43. Featuring a 30-megapixel sensor and RAW file format support, it's a perfect choice for professional photographers.",
  },
  {
    id: 165,
    img: nikon5,
    title: "nikon 43",
    price: 46999,
    company: "nikon",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Capture every detail with the Nikon 43. This camera offers a 30-megapixel resolution and RAW file format support, making it an ideal companion for photography enthusiasts.",
  },
  {
    id: 166,
    img: sony1,
    title: "Sony 44",
    price: 42999,
    company: "Sony",
    type: "camera",
    resolution: "24mp",
    fileformat: "jpeg",
    description:
      "Unleash your creativity with the Sony 44 camera. Featuring a 24-megapixel sensor, it captures high-quality images with rich details. Save your memories in JPEG format for easy sharing and storage.",
  },
  {
    id: 167,
    img: sony2,
    title: "Sony 43",
    price: 43999,
    company: "Sony",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Explore the world of photography with the Sony 43 camera. Boasting a 30-megapixel sensor, it enables you to capture stunning images with maximum detail. Shoot in RAW format for complete post-processing control.",
  },
  {
    id: 168,
    img: sony3,
    title: "Sony 44",
    price: 42999,
    company: "Sony",
    type: "camera",
    resolution: "24mp",
    fileformat: "jpeg",
    description:
      "Experience the brilliance of photography with the Sony 44 camera. Equipped with a 24-megapixel sensor, it delivers exceptional image quality. Save your moments in JPEG format for convenient sharing and storage.",
  },
  {
    id: 169,
    img: sony4,
    title: "Sony 43",
    price: 43999,
    company: "Sony",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Elevate your photography skills with the Sony 43 camera. With a 30-megapixel sensor, it captures vibrant images with outstanding detail. Shoot in RAW format for ultimate post-processing control.",
  },
  {
    id: 170,
    img: sony5,
    title: "Sony 43",
    price: 43999,
    company: "Sony",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Capture every detail with the Sony 43 camera. Boasting a 30-megapixel sensor, it delivers exceptional image quality. Save your images in RAW format for complete creative control during post-processing.",
  },
  {
    id: 171,
    img: canon1,
    title: "Canon 44",
    price: 42999,
    company: "Canon",
    type: "camera",
    resolution: "24mp",
    fileformat: "jpeg",
    description:
      "Capture stunning moments with the Canon 44 camera. Equipped with a 24-megapixel sensor, it delivers high-quality images. Save your memories in JPEG format for easy sharing and storage.",
  },
  {
    id: 172,
    img: canon2,
    title: "Canon 43",
    price: 43999,
    company: "Canon",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Unleash your creativity with the Canon 43 camera. Boasting a 30-megapixel sensor, this camera lets you capture detailed and sharp images. Shoot in RAW format for maximum post-processing flexibility.",
  },
  {
    id: 173,
    img: canon3,
    title: "Canon 44",
    price: 42999,
    company: "Canon",
    type: "camera",
    resolution: "24mp",
    fileformat: "jpeg",
    description:
      "Experience photography like never before with the Canon 44 camera. Featuring a 24-megapixel sensor, it delivers impressive image quality. Save your moments in JPEG format for convenient sharing and storage.",
  },
  {
    id: 174,
    img: canon4,
    title: "Canon 43",
    price: 43999,
    company: "Canon",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Elevate your photography game with the Canon 43 camera. With a 30-megapixel sensor, it captures detailed and vibrant images. Shoot in RAW format for complete creative control during post-processing.",
  },
  {
    id: 175,
    img: canon5,
    title: "Canon 43",
    price: 43999,
    company: "Canon",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Unlock the potential of your photography with the Canon 43 camera. Boasting a 30-megapixel sensor, it delivers exceptional image quality. Capture in RAW format for ultimate flexibility in post-processing.",
  },
  {
    id: 176,
    img: leica1,
    title: "leica 44",
    price: 42999,
    company: "leica",
    type: "camera",
    resolution: "24mp",
    fileformat: "jpeg",
    description:
      "Introducing the leica 44, a cutting-edge camera with 24 megapixels resolution and JPEG file format. Capture moments in stunning detail with this exceptional device.",
  },
  {
    id: 177,
    img: leica2,
    title: "leica 43",
    price: 43999,
    company: "leica",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Explore the world of photography with the leica 43. Boasting a 30-megapixel sensor and RAW file format support, it's a versatile tool for professional photographers.",
  },
  {
    id: 178,
    img: leica3,
    title: "leica 44",
    price: 42999,
    company: "leica",
    type: "camera",
    resolution: "24mp",
    fileformat: "jpeg",
    description:
      "Elevate your photography experience with the leica 44. This camera features a 24-megapixel resolution and supports JPEG file format for high-quality images.",
  },
  {
    id: 179,
    img: leica4,
    title: "leica 45",
    price: 43999,
    company: "leica",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Capture the essence of every moment with the leica 43. With a 30-megapixel sensor and RAW file format, it's the perfect companion for creative photography.",
  },
  {
    id: 180,
    img: leica5,
    title: "leica 43",
    price: 43999,
    company: "leica",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Unleash your photographic potential with the leica 43. Featuring a 30-megapixel resolution and RAW file format support, it's a reliable choice for photography enthusiasts.",
  },
  {
    id: 181,
    img: lumix1,
    title: "lumix 44",
    price: 42999,
    company: "lumix",
    type: "camera",
    resolution: "24mp",
    fileformat: "jpeg",
    description:
      "Experience photography like never before with the Lumix 44. This camera boasts a 24-megapixel resolution and supports JPEG file format for crisp and vibrant images.",
  },
  {
    id: 182,
    img: lumix2,
    title: "lumix 43",
    price: 43999,
    company: "lumix",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Unleash your creativity with the Lumix 43. Featuring a powerful 30-megapixel sensor and RAW file format support, it's the perfect companion for professional photographers.",
  },
  {
    id: 183,
    img: lumix3,
    title: "lumix 44",
    price: 42999,
    company: "lumix",
    type: "camera",
    resolution: "24mp",
    fileformat: "jpeg",
    description:
      "Capture stunning moments with the Lumix 44. With a 24-megapixel resolution and JPEG file format, this camera delivers exceptional image quality for photography enthusiasts.",
  },
  {
    id: 184,
    img: lumix4,
    title: "lumix 43",
    price: 43999,
    company: "lumix",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Elevate your photography game with the Lumix 43. Boasting a 30-megapixel sensor and RAW file format support, it offers versatility for both amateurs and professionals.",
  },
  {
    id: 185,
    img: lumix5,
    title: "lumix 43",
    price: 43999,
    company: "lumix",
    type: "camera",
    resolution: "30mp",
    fileformat: "raw",
    description:
      "Capture every detail with the Lumix 43. This camera features a 30-megapixel resolution and RAW file format support, providing endless possibilities for creative expression.",
  },
];
export default productData;
